FROM ubuntu:bionic

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      make \
      g++ \
      liblapack-dev \
      liblapacke-dev \
      libopenblas-dev \
      python3-pip \
      wget \
      && \
    apt-get autoremove --purge -y && \
    apt-get autoclean -y && \
    pip install cmake && \
    rm -rf /var/cache/apt/* /var/lib/apt/lists/*
